- CHANGELOG.md
- src/pixelator/analysis/colocalization/__init__.py
- src/pixelator/analysis/colocalization/types.py
- tests/analysis/colocalization/test_colocalization.py
This removes the unused clr and relative transformation types from the colocalization analysis.
Fixes: https://linear.app/pixelgen-technologies/issue/EXE-908/remove-clr-and-relative-transformations-from-colocalization
Tested with unit tests. I also added a unit test for computing colocalization with a log1p transformation that was missing from the test suite.
> Remove clr and relative transformations from colocalization

- .github/workflows/publish-pypi.yml
- poetry.lock
Add a workflow for publishing to pypi or testpypi. This uses the PyPI "Trusted Publishers" feature to fetch a short lived OIDC token.
> Add PyPI publishing workflow

- src/pixelator/report/webreport/builder.py
- src/pixelator/report/webreport/types.py
> chore: update to report 0.8.0

- CHANGELOG.md
- tests/test_pixeldataset.py
Prepare Pixelator 0.15.2 for release.
> Prepare Pixelator 0.15.2 release

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .vscode/settings.json
- DEVELOPERS.md
Make the vscode devcontainer use python 3.11, and fix up some other random issues with it.
> Update devcontainer to use py3.11

- .github/workflows/tests.yml
This adds codecov for test coverage analysis to the pixelator repo.
> Add codecov uploads

- src/pixelator/graph/backends/implementations.py
- src/pixelator/graph/backends/protocol.py
- tests/graph/test_graph.py
Get the connected components from a `networkx` based graph. These changes look way more extensive than they actually are since I had to move some code around to get rid of some circular import issues.
Fixes: EXE-1097
Tested with the unit test suite, I've also tried this on some large-ish samples locally to see that it give the same results.
> Get connected components with networkx

- .flake8
Remove DOC501 checks from .flake8 for more accurate doc style checking.
> Remove DOC501 from .flake8

- CHANGELOG.md
- src/pixelator/graph/backends/implementations/_igraph.py
- src/pixelator/graph/backends/implementations/_networkx.py
- src/pixelator/graph/backends/protocol.py
- src/pixelator/graph/graph.py
- tests/graph/conftest.py
- tests/graph/test_graph.py
This adds the capability to compute graph layouts using networkx as the Graph backend.
With unit tests, and by running manual experiments locally.
> Compute layouts using networkx

- src/pixelator/graph/backends/implementations/_networkx.py
- src/pixelator/graph/utils.py
- tests/analysis/polarization/test_polarization.py
- tests/conftest.py
- tests/graph/backends/test_implementations.py
- tests/graph/igraph/test_tools.py
Move all tests to using networkx as their backend.
Fixes: EXE-1263
This has been tested by running the unit test suite.
> Move all tests to use networkx

- CHANGELOG.md
- README.md
Patch release 0.16.1 for pixelator.
> Release 0.16.1

- .flake8
- CHANGELOG.md
- src/pixelator/amplicon/process.py
- src/pixelator/amplicon/statistics.py
- src/pixelator/cli/adapterqc.py
- src/pixelator/cli/amplicon.py
- src/pixelator/cli/analysis.py
- src/pixelator/cli/annotate.py
- src/pixelator/cli/collapse.py
- src/pixelator/cli/common.py
- src/pixelator/cli/demux.py
- src/pixelator/cli/graph.py
- src/pixelator/cli/logging.py
- src/pixelator/cli/main.py
- src/pixelator/cli/preqc.py
- src/pixelator/cli/report.py
- src/pixelator/collapse/process.py
- src/pixelator/types.py
- src/pixelator/utils.py
- tests/amplicon/test_statistics.py
- tests/utils/test_utils.py
- Properly handle log messages from process pool workers.
- Verbose mode now forwards debug log messages to console output.
- Normal mode now prints all INFO level logs to the console.
- Remove duplication between log.info and click.echo
Fixes: EXE-1342
> Fix multiprocess logging

- CHANGELOG.md
- src/pixelator/graph/backends/implementations/_networkx.py
- src/pixelator/graph/backends/protocol.py
- src/pixelator/graph/graph.py
- tests/graph/test_graph.py
This PR adds the PMDS layout algorithm which is available in R from the `graphlayouts` package. [Here](https://github.com/schochastics/graphlayouts/blob/main/R/layout_large_graphs.R)'s the source code for the R implementation. You can also have a look at the original publication [here](https://link.springer.com/chapter/10.1007/978-3-540-70904-6_6).
The PMDS algorithm runs multidimensional scaling on a graph's distance matrix to create coordinates into an abstract Cartesian space. The P refers to a set of randomly sampled pivot nodes which are used to subset the distance matrix and speed up the computation. 
Fixes: EXE-1352
**Test Configuration**:
* Firmware version:
* Hardware: Apple M2 Pro
* Toolchain:
* SDK:
> Added PMDS layout method

- CHANGELOG.md
- src/pixelator/analysis/colocalization/statistics.py
- tests/analysis/colocalization/test_colocalization.py
- tests/analysis/colocalization/test_estimate.py
- tests/analysis/colocalization/test_statistics.py
Remove self-correlation values from colocalization results
Fixes: EXE-968
Unit tests.
> Remove self-correlation values from colocalization

- CHANGELOG.md
- src/pixelator/plot/__init__.py
- src/pixelator/plot/constants.py
- tests/plot/test_plot.py
- tests/snapshots/test_plot/test_scatter_umi_per_upia_vs_tau/scatter_umi_per_upia_vs_tau.json
Added a QC plot function to compare the UMIs per UPIA against Tau scores.
Fixes: EXE-1356
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:
> Added pxContent_vs_Tau QC plot function to plot module.

- src/pixelator/pixeldataset/precomputed_layouts.py
- tests/pixeldataset/test_precomputed_layouts.py
Lazy load components and select which columns you want.
Fixes: exe-1329
Unit tests.
> Add column filtering to iterator/to_df methods

- src/pixelator/logging.py
- tests/test_logging.py
Unhandled exceptions were not propagated to the log properly, I think that makes sure that they do.
Fixes: EXE-1458
I have manually tested this by adding exceptions in different context in the code and verified that they get logged, i.e. in a "normal" context, a multithreading context and in a multiprocessing context.
> Ensure unhandled exceptions get logged

- .dockerignore
- .github/actions/build-dev-image/action.yml
- .github/workflows/build.yml
- .github/workflows/checks.yml
- .github/workflows/docs.yml
- .github/workflows/tests.yml
- containers/base.Dockerfile
- containers/dev.Dockerfile
- containers/prod.Dockerfile
- docker-bake.hcl
This PR adds various containers related bits.
- Add some standard labels following the opencontainers annotations spec to the docker images and update the GH actions workflow to insert auto generated labels from the repo information.
- The base image is updated to fedora:39
- Build the package first in the container to make sure versions are reported properly
Fixes: EXE-1482
> Update docker containers build workflow

- src/pixelator/logging.py
- src/pixelator/utils.py
- tests/utils/test_utils.py
Better logging in multiprocessing scenarios. 
Also allows some of our sanity check functions to take a single `PathType` to make them a bit more user friendly.
Fixes: EXE-1496
Tested as part of the work I've been doing on the `layout` stage (a PR is incoming shortly).
> Fixes in utils and improved multiprocess logging

- CHANGELOG.md
Added the new differential colocalization functions in the CHANGELOG.
> Added the new differential colocalization functions in the CHANGELOG.

- CHANGELOG.md
- src/pixelator/feature_flags.py
- tests/test_feature_flags.py
Add a basic feature flag module.
Fixes: exe-1487
Unit tests.
> Add basic feature flag module

- CHANGELOG.md
Prepare the change log for the release of 0.17.0.
> Prepare change log for release of 0.17.0

- CHANGELOG.md
Prep changelog for 0.17.1 release.
> Changelog for 0.17.1

- poetry.lock
- src/pixelator/report/common/reporting.py
- tests/report/test_reporting.py
Small change to support plugin commands in the qc-report parameters overview.
Fixes: EXE-1860
> Allow plugin commands in qc report Parameters section

- CHANGELOG.md
- src/pixelator/cli/analysis.py
Make `rate-diff` the default transformation in colocalization
Fixes: exe-1861
Unit tests.
- [] I have added tests that prove my fix is effective or that my feature works
- [] If a new tool or package is included, I have updated poetry.lock, and [cited it properly](../CITATIONS.md)
> rate-diff default transformation in colocalization

- .github/actions/build-dev-image/action.yml
Fix some typo issues with the latest CI update
> Fix syntax error in container build action

- CHANGELOG.md
Please include a summary of the change and which issue(s) have been fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes: #(issue number)
This is a PR for a release 0.18
> Release 0.18 prep

- CITATIONS.md
- README.md
Please include a summary of the change and which issue(s) have been fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes: TECH-130
This is just a documentation fix that needed to be done where we change our bioRxiv citations to the final nature paper publication.
I don't think it needs to be updated in the CHANGELOG.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce it when relevant.
Not tested as it is only docs.
> fix: citations to the nat methods paper in the repo

- containers/dev.Dockerfile
- src/pixelator/resources/assays/D21.yaml
- Some cosmetic fixes in the assay file region names.
- Only install dev packages in the dev Container file. All main packages are already installed in the base layer
> Fix some typos and tweak development Dockerfile 

- src/pixelator/pna/cli/graph.py
Fix missing import in PNA graph step.
Fixes: -
By running the graph step manually.
- [] I have added tests that prove my fix is effective or that my feature works
> Fix missing import in pna graph step

- CHANGELOG.md
Update the change log for pixelator 0.20.0.
> Prepare 0.20.0 release of pixelator

- README.md
Mention the Proximity Network Assay in the README.
> Add PNA to README

- .github/workflows/checks.yml
- CHANGELOG.md
- src/pixelator/common/utils/units.py
- src/pixelator/pna/cli/common.py
- src/pixelator/pna/cli/demux.py
- src/pixelator/pna/demux/barcode_demuxer.py
- src/pixelator/pna/demux/pipeline.py
- src/pixelator/pna/demux/process.py
- tests/pna/data/intermediate-demux-results/tmp/PNA055_Sample07_filtered_S7.demux.m1.part_000.parquet
- tests/pna/data/intermediate-demux-results/tmp/PNA055_Sample07_filtered_S7.demux.m2.part_000.parquet
- tests/pna/demux/conftest.py
- tests/pna/demux/test_barcode_demuxer.py
- tests/pna/demux/test_demux_writer_process.py
- tests/pna/demux/test_integration.py
- tox.ini
Large intermediate input arrow files are becoming corrupted during the removal of identical molecules and sorting at the end of the pna demux stage. It looks like a pyarrow bug so we are replacing that with duckdb here to workaround the issue. 
Fixes: PNA-876
> Workaround pyarrow issue in pna demux

- CHANGELOG.md
- containers/base.Dockerfile
Install missing gzip dependency in the containers. This is needed for the nf-core/pixelator stub tests, which assume that this will be available.
Docker container update.
Tested manually with the nf-core/pixelator tests locally using the container built here.
> Install gzip in container

- .github/actions/setup-image-build-env/action.yml
- .github/workflows/build.yml
Fix secret passing for quay login.
> Pass quay user/passwd from workflow to action
