PixelgenTechnologies/pixelator

CHANGELOG.md
pyproject.toml
tests/conftest.py
tests/integration/conftest.py

Fix an issue where the pytest `--keep-workdirs` cli option would only work when running integration tests using `pytest tests/integration` and when running all tests from the project root.
Fixes: EXE-1055

Fix tests `--keep-workdirs` flag

---

.flake8
CHANGELOG.md
poetry.lock
pyproject.toml
src/pixelator/analysis/colocalization/prepare.py
src/pixelator/annotate/__init__.py
src/pixelator/graph/community_detection.py
src/pixelator/graph/graph.py
src/pixelator/graph/utils.py
src/pixelator/pixeldataset.py
tests/analysis/colocalization/test_prepare.py
tests/conftest.py
tests/graph/test_graph.py
tests/graph/test_graph_utils.py
tests/test_pixeldataset.py
tests/test_tools.py

First of all, sorry that this is such a huge PR, but this touches on a lot different things.
This introduces:
- smaller in memory edge lists (~60% of the original dataframe size in my benchmarks)
- less memory intensive concatenation (~23% of the original memory usage)
- lazy data frame representation of the edge list using polars `LazyFrame`. This allows us to carry out many operations on the edge list without loading all of it into memory, which should improve scalability in many cases.
- the lazy data frames are now used, for checking the edge list size, filtering `PixelDataset` instances, concatenation, and finding individual components in the edgelist
These changes are backward compatible, but there will be a performance hit (higher memory usage, and longer runtimes) when working …

Smaller (in-memory) and lazy edge lists

---

CHANGELOG.md
src/pixelator/cli/adapterqc.py
tests/integration/conftest.py

Remove unneeded --pbs1 and --pbs2 flags to adapterqc.
Customizig these values should happen through assay files.
Fixes: EXE-943

Remove adapterqc pbs flags

---

.github/actions/build-dev-image/action.yml
.github/workflows/publish-pypi.yml
.github/workflows/tests.yml

- Some fixes to the publishing workflow after testing.
- Add a version check before uploading to see the release tag matched the pixelator version.
Fixes [EXE-1147](https://linear.app/pixelgen-technologies/issue/EXE-1147/create-pypi-publishing-action-on-release)

Fix publishing workflow

---

.github/workflows/publish-pypi.yml
CHANGELOG.md
containers/base.Dockerfile
containers/dev.Dockerfile
pyproject.toml
src/pixelator/pixeldataset.py
tests/annotate/test_aggregates.py

Add python 3.11 to supported versions now that all depencies support 3.11.
This also changes github actions and the docker containers to use 3.11.
Fixes [EXE-798](https://linear.app/pixelgen-technologies/issue/EXE-798/support-python-311-in-pixelator)
Test suite, test suite in updated containers

feat: Add support for python 3.11

---

.github/workflows/workflow-tests.yml
src/pixelator/test_utils/collector.py
tests/integration/external_tests/readme.md
tests/integration/test_full_D21.yaml

Enable the workflow tests on private GH action runners again.
This also improves workflow test loading by not needing the yaml file to be in a python module (with `__init__.py` file in the directory).
Fixes: [EXE-878](https://linear.app/pixelgen-technologies/issue/EXE-878/update-aws-large-scale-test-for-0131)
Manual testruns of the actions.

Fix workflow tests on external action runners

---

CHANGELOG.md
pyproject.toml
src/pixelator/pixeldataset.py
tests/test_pixeldataset.py

The sample name was missing from the concatenated edge lists. This bug was introduced when I switched to using polars for concatenating the edge lists. This fixes that, and makes sure that the tests catches this problem.
Fixes: EXE-1174
Tested with the unit test suite, including new test code to verify that this bug has been fixed.

Fix sample column missing from concatenated edgelist

---

CHANGELOG.md
src/pixelator/graph/backends/implementations.py
src/pixelator/pixeldataset.py
tests/graph/test_graph_utils.py
tests/test_pixeldataset.py

This fixes two bugs, see below.
Fixes:
- Problem when filtering an aggregated pixeldataset (EXE-1177)
- Problem when generating graph layouts, caused by an incorrect data frame concatenation
Tested by running, and writing new datasets, and by running the cell visualization tutorial where some of these problems popped up.
Tested by running, and writing new datasets, and by running the cell visualization tutorial where some of these problems popped up.

Fix filtering edgelist bug, and layout generation problem

---

CHANGELOG.md
src/pixelator/pixeldataset.py
tests/test_pixeldataset.py

Fixes the following issues:
- aggregation of more than two pixeldatasets was broken.
- indexes were written to the parquet files, which caused downstream issues.
Fixes: EXE-1184
With unit tests, as well as by manually verifying that it works in the scenario where the bug was originally reported.

Fixes to pixeldataset aggregation and parquet file indexeing

---

CHANGELOG.md
src/pixelator/graph/backends/implementations/__init__.py
src/pixelator/graph/backends/implementations/_networkx.py
src/pixelator/graph/backends/protocol.py
src/pixelator/graph/graph.py
tests/graph/backends/test_implementations.py
tests/graph/conftest.py
tests/graph/test_graph.py

`add_edges` was always assuming the backend was igraph based. This prompted me to take a closer look at how we instantiate `Graph` instances from "raw" graphs, which we only do in the tests. This PR cleans this up this interface and makes sure that we get the correct underlying backend depending on which type of "raw" graph input is given.
I also switched `PIXELATOR_GRAPH_BACKEND="NetworkXGraphBackend"` to be the mechanism for switching the graph according to @fbdtemme suggestion in #45 .
Fixes: EXE-1242
Tested with the unit tests.

Feature/exe 1242 `add_edges` was always assuming backend is igraph based

---

CHANGELOG.md
src/pixelator/cli/analysis.py
src/pixelator/graph/graph.py
tests/analysis/polarization/test_polarization.py
tests/conftest.py
tests/graph/conftest.py
tests/graph/networkx/__init__.py
tests/graph/networkx/test_tools.py
tests/graph/test_graph.py

- Fixes incorrect formatting in analysis command cli docs.
- Exposes that `raw` property of the `Graph` object as a public property.
With unit tests and by manually looking at the docs.

Formatting fixes, and exposing `raw` as public property

---

tests/annotate/test_annotate.py

The Leiden cluster test was failing, since the naming of the clusters is not deterministic.
Fixes: EXE-1323
Tested by running unit test suite.

Check exected groups in leiden cluster test

---

CHANGELOG.md
src/pixelator/cli/analysis.py
src/pixelator/collapse/process.py
tests/collapse/test_process.py

Fix an issue were read counts in the edgelist are deflated because the counts of collapsed reads are not taken into account.
Only the reads of unique matches to the corrected read were reported and not the reads of other molecules that have mismatches.
Fixes: EXE-1250

Fix deflated counts in edgelist after collapse

---

CHANGELOG.md
src/pixelator/report/__init__.py
tests/report/test_report.py

Calculate discarded UMIs based on data from collapse, graph, annotate and cell calling as opposed to just using discarded aggregates.
Fixes TECH-29
Generate QC report with updated code by running:
`pixelator single-cell report`

Fix bug in calculation of discarded UMIs

---

CHANGELOG.md
src/pixelator/cli/adapterqc.py
src/pixelator/cli/amplicon.py
src/pixelator/cli/analysis.py
src/pixelator/cli/annotate.py
src/pixelator/cli/demux.py
src/pixelator/cli/graph.py
src/pixelator/cli/preqc.py
src/pixelator/config/panel.py
src/pixelator/utils.py
tests/amplicon/test_cli.py
tests/utils/test_utils.py

Remove parallel processing of multiple samples in a single command. 
This feature is better handled by using the nextflow pipeline.
The only parallel handling remaining on the input file level is in collapse to deal with the demuxed fastq files.
The `amplicon` subcommand interface is changed: 
The also removes `--input1-pattern` and `--input2-pattern` since these have become redundant.
Add a --sample-name flag to use a custom output filename instead of extracting a sample name from the input fastq files.
Fixes: EXE-1341

Remove multi-sample processing

---

CHANGELOG.md
src/pixelator/utils.py
tests/utils/test_utils.py

Sample name matching should only match file name, not full path.
Fixes: EXE-1390 
Unit tests.

Sample name matching should only match file name, not full path.

---

.flake8
CHANGELOG.md
src/pixelator/graph/graph.py
tests/graph/test_graph.py

Adds a `__repr__` method to the `Graph` class to give some nice output in e.g. jupyter notebooks.
Fixes: EXE-915
Unit tests and by trying it in ipython.

Add __repr__ method to graph

---

.pre-commit-config.yaml
CHANGELOG.md
src/pixelator/analysis/__init__.py
src/pixelator/annotate/__init__.py
src/pixelator/report/__init__.py
src/pixelator/report/qcreport/collect.py
src/pixelator/test_utils/analysis.py
src/pixelator/test_utils/annotate.py
tests/annotate/test_annotate.py
tests/report/test_report.py

This adds the stage name, i.e. `annotate`/`analysis` the the names of pixel files when they are generated by their respective commands.
Fixes: EXE-1347
Using the unit test suite.

Add step names to pxl file names

---

pyproject.toml
src/pixelator/annotate/__init__.py
src/pixelator/graph/backends/implementations/_networkx.py
tests/graph/test_graph.py

Importing `graspologic` and `scanpy` is slow, so I have moved these to only be imported when needed at runtime. This speeds up pixelator start-up times and tests considerably. Cold startups going from ~9s -> 2s (your milage might very depending on what has been cached etc). And also shaving of up to ~1/3 of the startup time when running tests, which is why I started looking into this in the first place.

Speed up init time by making some imports dynamic

---

.vscode/settings.json
src/pixelator/pixeldataset/datastores.py
src/pixelator/pixeldataset/precomputed_layouts.py
tests/pixeldataset/test_precomputed_layouts.py

This PR fixes a problem we have with writing large pxl-files larger than 2Gb. This is related to this issue in https://github.com/fsspec/filesystem_spec/issues/1474
It also fixes some other issues I found:
- Using pyarrow to write caused us to have smaller row groups in the parquet files which gave us much worse compression rations (files growing up to twice the size)
- Make sure we use `zstd` compression instead of the default `snappy` for better compression rates
- A bug that caused aggregation to fail when there are no precomputed layouts in the file
Fixes:
- EXE-1450
I have run aggregation of a bunch of very large pxl files (without precomputed layouts), and it write an output file larger than 2Gb.

Fails to write very large pxl files

---

.pre-commit-config.yaml
CHANGELOG.md
poetry.lock
src/pixelator/report/common/workdir.py
src/pixelator/utils.py
tests/collapse/test_process.py
tests/report/test_collapse.py
tests/utils/test_utils.py
utils/check_copyright.py

read1 and read2 suffixes where checked in the whole filename instead of just the end to deal with illumina suffixes like in `SampleName_S1_L001_R1_001.fastq.gz`. This can causes issues when multiple patterns are recognised. We now check for a 3 digit suffix specificly and anchor all patterns to the end.
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes: EXE-1468
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
New tests in `tests/utils/test_utils.py`

Fix a bug in `is_read_file`

---

src/pixelator/plot/__init__.py
tests/plot/test_plot.py

Small PR just setting the default color when no marker is given in plot_3d_graph.

plot_3d_graph set to default color when no marker is given.

---

CHANGELOG.md
src/pixelator/cli/analysis.py

Cherry pick fix to `--polarization-n-permutations` from `dev` to make sure we can release 0.16.2 fixing the issue that this parameter was uninitialized.
Fixes: EXE-1362
Hotfix plus release notes.
We ran `pixelator single-cell analysis` and check that it was initialized to `0` rather than `None`.

Release 0.16.2

---

CHANGELOG.md
src/pixelator/analysis/polarization/__init__.py
tests/analysis/polarization/test_polarization.py

This moves marker filtering to be performed after count transformation and permutation in polarization score calculation in `polarization_scores_component_graph`. This removes bias of filtering parameters on the transformation and permutation.
This has become relevant since the introduction of the `polarization_min_marker_count` parameter, which affects which markers will be filtered prior to polarization score calculation. The bias was present before, but was predictable since there was no way for users to affect which markers were filtered. 
This is a breaking change, since the current transformation (non-negative CLR) takes all markers into account. 
Fixes: exe-1565
A new test has been added to verify that filtering parameters do not change …

fix: marker filtering after transformation in polar score

---

CHANGELOG.md
src/pixelator/utils/__init__.py
tests/utils/test_utils.py

Fix a bug where the wrong read 1/2 suffix is stripped away causing the pipeline to file due to mismatches sample names 
between r1 and r2 read pairs.
Fixes: EXE-1633

fix removal of wrong read 1/2 id when multiple matches are present

---

CHANGELOG.md
src/pixelator/graph/backends/implementations/_networkx.py
src/pixelator/graph/backends/protocol.py
src/pixelator/graph/graph.py
src/pixelator/pixeldataset/precomputed_layouts.py
tests/conftest.py
tests/graph/test_graph.py
tests/pixeldataset/test_precomputed_layouts.py

This adds an option on graph creation `convert_indices_to_integers` that allows us to bypass the conversion of node indices to integers. This defaults to `True` to keep the current behavior.
Being able to keep the node names as their original strings is important if you need to reattach edges to nodes at a later point in the analysis.
Fixes: exe-1662
Manually, as well as with unit tests.

`convert_indices_to_integers` option

---

CHANGELOG.md
src/pixelator/analysis/__init__.py
src/pixelator/analysis/polarization/__init__.py
src/pixelator/analysis/polarization/types.py
src/pixelator/cli/analysis.py
tests/analysis/polarization/test_polarization.py

Remove `clr` and use instead use `log1p` as default polarity score transformation.
Fixes: EXE-1542
By unit tests. @maxkarlsson has done analysis to verify the change itself.

Remove clr and use log1p as default polarity score transformation

---

src/pixelator/analysis/__init__.py

One comment was missed in feature/exe-1542-switch-from-clr-to-log1p-as-default-polarity-transformation. This resolves that comment. 
Fixes: exe-1542
Test suite

fix: missed transformation

---

CHANGELOG.md
CITATIONS.md
src/pixelator/graph/graph.py
src/pixelator/graph/node_metrics.py
tests/graph/test_graph.py
tests/graph/test_node_metrics.py

Adding `compute_transition_probabilities` and `local_g` functions. `compute_transition_probabilities` takes an adjacency matrix as input and returns a matrix with transition probabilities between node pairs for a k-step random walk. `local_g` takes an adjacency matrix and a marker count matrix as input and returns a DataFrame with local G scores per marker and node. By default, `local_g` uses transition probabilities for a k-step random walk (`compute_transition_probabilities`) to construct a weighting scheme for the metric computation. 
The main expected use case of local G scores is for visualizing spatial trends of marker expression on 2D/3D layouts.
`local_g` is provided as a separate function within the new `node_metrics` module and can also be called as a method on Graph objects. …

Added local_g

---

CHANGELOG.md
src/pixelator/analysis/colocalization/__init__.py
src/pixelator/analysis/colocalization/types.py
src/pixelator/statistics.py
tests/analysis/colocalization/test_colocalization.py
tests/test_statistics.py

rate_diff_transformation is an alternative transformation that has been shown to improve the raw pearson values for colocalization analysis especially in terms of removing the correlation between colocalization values and marker abundance. It is now being added as an option but will not be set as the default transformation yet for colocalization analysis (the default is currently log1p). 
Added a unit-test for colocalization calculation with rate-diff transformation to verify run without errors. The colocalization values with rate-diff transformation are also checked for different datasets and are shown to result in high agreement between raw pearson values and pearson_z scores and expected biological signals such as HLA-ABC with B2M and CD11a …

Adding the rate_diff_transformation function.

---

CHANGELOG.md
src/pixelator/pixeldataset/datastores.py

Write performance degraded when writing layouts for many small components, taking 1.5h+ for ~3000 components of 2-5 vertices in size (like we currently have in the nf-core/pixelator test data). This brings that back into a total runtime of ~2 min which is more manageable.
Fixes: EXE-1751
Performance fix.
Unit tests and by manually running layouts on files locally.

Fix write performance for many small layouts

---

CHANGELOG.md
src/pixelator/pixeldataset/datastores.py

Release 0.17.1

---

CHANGELOG.md
src/pixelator/analysis/__init__.py
src/pixelator/analysis/colocalization/__init__.py
src/pixelator/cli/analysis.py
tests/Taskfile.yml
tests/analysis/colocalization/test_colocalization.py
tests/analysis/test_analysis_engine.py
tests/conftest.py
tests/graph/networkx/test_tools.py
tests/integration/test_small_D21.yaml

Exclude low-count markers in a component from colocalization calculation.
Fixes: EXE-1826
The existing tests pass. A new test is added to remove markers with low counts from a component and check how many marker-pairs are included in colocalization output.

Implement low-count marker removal in pixelator colocalizaiton

---

.github/actions/build-dev-image/action.yml

Make sure containers created on tag events override the dynamic pixelator version.
Remove unused input argument
Fixes: EXE-1880

ci: fix pixelator container version on tag push

---

containers/base.Dockerfile
containers/prod.Dockerfile

After updating to a new Amazon Linux container the local development containers file to run on AWS Batch due to the
aws-cli trying to load a pixelator specific package instead of its own version.
The aws-cli is mounted inside the container by nextflow so we need to remove the use of `PYTHONPATH` since that will interfer with the aws-cli dependencies.
All packages installed to the custom `PYTHONPATH` location have been moved so the containers play nice again with nextflow
with `export PYTHONNOUSERSITE=1`.

Fix local development container builds running with PYTHONNOUSERSITE on AWS

---

.github/workflows/tests.yml
poetry.lock
src/pixelator/report/common/json_encoder.py
tests/Taskfile.yml
tox.ini

Update testing gh workflows using tox.
- Streamline the use of poetry and the way the package is installed.
- Use the tox-gh plugin instead of a manual script to map workflow matrix versions to tox versions

Fix running tests with tox and rework testing workflow

---

src/pixelator/graph/community_detection.py
src/pixelator/pixeldataset/utils.py

Since graspologic takes a long time to import we have had those imports done dynamically as they are needed rather than at the module level. This speeds up cli start up times considerably. 
I also cleaned out some unused imports.
Fixes: N/A
Only changes when things are imported.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce it when relevant.

Improve cli start-up speed

---

src/pixelator/pixeldataset/__init__.py

graph = pxl.graph("missing_component_id") results in a ComputeError instead of a KeyError. 
Fixes: EXE-2058
The tutorial example that was raising a ComputeError raises a KeyError now.

Fixing the error output for calling pixel graph function with non-existing component name

---

CHANGELOG.md
src/pixelator/graph/backends/implementations/_networkx.py
tests/pixeldataset/test_precomputed_layouts.py

Check up-front that the number of nodes is greater than the number of dimensions being requested in the pmds layout - if not give a clearer error message.
Fixes: exe-2061
Unit test added and some manual testing.

Better error message when there are fewer nodes than the number of dimensions in pmds layout

---

CHANGELOG.md
src/pixelator/graph/backends/implementations/_networkx.py
src/pixelator/graph/backends/protocol.py
src/pixelator/graph/graph.py
src/pixelator/graph/node_metrics.py

In some scenarios local g will return scrambled results due to inconsistent node ordering. This fixes that.
Fixes: exe-2084
Unit tests, and by manual tests on failing components.

Exe 2084 bug in local g

---

src/pixelator/pna/cli/analysis.py
src/pixelator/pna/cli/layout.py
src/pixelator/pna/pixeldataset/__init__.py
tests/pna/pixeldataset/test_pna_pixeldataset.py

Make it a bit easier to work with the `read` function by making sure that it will also accept raw strings as input. They will then be internally converted to `Path` and passed along. This removes the need for users to always import `pathlib` which I think might be a bit more accessible to folks who are new to bioinformatics/python.
Fixes: -
Added unit tests and manually tried it out.

Read function accepts a list of strings

---

src/pixelator/pna/config/config_instance.py
src/pixelator/pna/config/plugin.py

Enabling addition of plugins for PNA configuration.
Fixes: PNA-883
Existing unit tests.

Enable config update from plugins

---

CHANGELOG.md
src/pixelator/pna/config/panel.py
tests/pna/config/test_panel.py

Check that there are no `_` in the panel marker ids, since these do not play well with Seurat downstream.
Added unit tests.

Validate there are no underscores in panel file marker ids

---

.github/workflows/cla.yml

Add a simple CLA checking & signing workflow.
Users that have not signed the CLA can do so by simply commenting on the PR.
> I have read the CLA Document and I hereby sign the CLA
To trigger the bot to recheck the CLA again you can comment
> recheck
A list of signatures will be stored in [PixelgenTechnologies/cla-signatures](https://github.com/PixelgenTechnologies/cla-signatures).
Fixes: EXE-1092
Tested in a seperate private test repo.

feat: add cla check action

---

src/pixelator/common/utils/units.py
src/pixelator/pna/cli/common.py
tests/pna/demux/test_demux_cli.py

We currently get an error when None is passed to _memory_validator. It is however expected to output None in that case.
Unit tests.

Passing None through _memory_validator in demux

---

CHANGELOG.md
src/pixelator/pna/pixeldataset/io/__init__.py

Use DuckDB read-only connections where appropriate to allow multiple python processes on
the same database file. This issue can pop up during testing of the nf-core pipelines when files are staged as symlinks.
Fixes: PNA-1231
Existing test suite, pipeline tests with nf-test.

Use read_only mode duckdb connection in PxlFile and PixelDataViewer

---

src/pixelator/common/graph/backends/implementations/_networkx.py
src/pixelator/pna/analysis_engine.py
src/pixelator/pna/graph/__init__.py
src/pixelator/pna/layout/__init__.py
src/pixelator/pna/pixeldataset/__init__.py
src/pixelator/pna/pixeldataset/io/__init__.py
tests/mpx/graph/test_graph.py
tests/pna/graph/test_graph.py

Calculating matrix power can become very expensive for adjacancy matrices, especially when there are nodes with many (>1000) edges resulting in power matrix becoming dense. A remedy to this implemented here is to set very small values (<0.001) to 0. In addition, to be able to avoid using polars as it appears to have some issues with releasing memory, we are refactoring PNA graph step to be able to construct networkx graphs using pyarrow instead of polars.
Fixes: PNA-1175
Existing tests pass and a large sample that was previously failining in the layout step can now go through it without issues.

Maintain sparsity in adjacency matrix power and refactor PNA graph construction

---

CHANGELOG.md
src/pixelator/pna/demux/barcode_identifier.py
tests/pna/demux/test_barcode_demuxer.py

Fix a bug in the metrics written to results.json of the PNA demux stage.
Input reads that failed because of both unrecoverable PID1 and PID2 are not properly accumulated in the failed reads statistic. The total is caluculated as passed + failed so that value too would be smaller than expected.
The number of reads that are failing in demux because of unrecoverable PID1 and PID2 is very small so most statistics were not effected in a meaningful way. (0.004 % of reads in the test sample).
Fixes: #PNA-1424
A new test case for the statistics accumulation.

PNA-1424: Fix demux statistics counter not accumulating `missing_pid1_pid2` counter

---

CHANGELOG.md
src/pixelator/pna/collapse/independent/collapser.py
src/pixelator/pna/collapse/paired/collapser.py

Collapsing very large PID groups where the combined marker array content exceeds 2 GiB would return an error when casting to the intermediary table format for sorting.
Explicitly use pa.large_string() instead for the table schema.
Please include a summary of the change and which issue(s) have been fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes: PNA-1486

Use pa.large_string for marker_1 / marker_2 columns
